
  bind:
    image: cytopia/bind:alpine-0.35
    container_name: ${COMPOSE_PROJECT_NAME}_bind
    hostname: bind
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      - DNS_A=${DNS_A}
      - DNS_FORWARDER=${DNS_FORWARDER}
    network_mode: bridge
    extra_hosts:
      - "host.docker.internal:host-gateway"
