  mailcatcher:
    image: mailhog/mailhog:latest
    container_name: ${COMPOSE_PROJECT_NAME}_mailcatcher
    restart: unless-stopped
    ports:
      - "${SURFACE_PORT:-8025}:8025"
      - "${SENDMAIL_PORT:-1025}:1025"
    depends_on:
      - bind-internal
    networks:
      dlbridge:
        ipv4_address: ${DL_MAILCATCHER_IPv4}
        aliases:
          - mailcatcher
    dns:
      - ${DL_BIND_INTERNAL_IPv4:-}
