  php80:
    image: degobbis/php80-fpm-alpine:latest
    container_name: ${COMPOSE_PROJECT_NAME}_php80
    hostname: php80
    links:
      - mailhog
      - ${DATABASE_TO_USE}
    volumes:
      - ./.config/php/php-fpm-global-overrides.conf:/usr/local/etc/php-fpm.d/zzz-php-fpm-global-overrides.conf:rw
      - ./.config/php/php80/php-fpm-overrides.conf:/usr/local/etc/php-fpm.d/zzzz-php-fpm-overrides.conf:rw
      - ./.config/php/php-global-overrides.ini:/usr/local/etc/php/conf.d/z00-php-global-overrides.ini:rw
      - ./.config/php/php-xdebug-3.x.ini:/usr/local/etc/php/conf.d/z10-php-xdebug-3.x.ini:rw
      - ${APP_BASEDIR:-./data}:/srv:rw
      - phpsocket:/run/php
    environment:
      TZ: ${MY_TZ:-UTC}
      LC_ALL: ${MY_LOCALES:-en_GB.UTF-8}
      APP_USER_ID: ${APP_USER_ID:-1000}
      APP_GROUP_ID: ${APP_GROUP_ID:-1000}
      PHP_ENV: ${PHP_ENV:-development}
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/conf.d/:/srv/php/php80/"
      XDEBUG_CONFIG: ""
      XDEBUG_SESSION: 1
      XDEBUG_REMOTE_HOST: ${REMOTE_HOST_IP}
    networks:
      net:
        ipv4_address: 172.16.238.14
