
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:fpm-alpine
    container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin
    hostname: phpmyadmin
    links:
      - ${DATABASE_TO_USE}
    volumes:
      - ./.config/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php:rw
      - pma:/var/www/html
    environment:
      TZ: ${MY_TZ:-UTC}
      LC_ALL: ${MY_LOCALES:-en_GB.UTF-8}
      PMA_HOST: mysql
      PMA_PORT: 3306
      MAX_EXECUTION_TIME: ${PMA_MAX_EXECUTION_TIME:-600}
      MEMORY_LIMIT: ${PMA_MEMORY_LIMIT:-512M}
      UPLOAD_LIMIT: ${PMA_UPLOAD_LIMIT:-512M}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD:-root}
    networks:
      net:
        ipv4_address: 172.16.238.17
