version: '3'
services:

  bind:
    image: cytopia/bind:0.15

  apache24:
    image: degobbis/apache24-alpine:latest

  php56:
    image: degobbis/php56-fpm-alpine:latest

  php73:
    image: degobbis/php73-fpm-alpine:latest

  php74:
    image: degobbis/php74-fpm-alpine:latest

  php80:
    image: degobbis/php80-fpm-alpine:latest

  php81:
    image: degobbis/php81-fpm-alpine:latest

  mariadb104:
    image: degobbis/mariadb104-alpine:latest

  mariadb105:
    image: degobbis/mariadb105-alpine:latest

  mariadb106:
    image: degobbis/mariadb106-alpine:latest

  mailhog:
    image: mailhog/mailhog:latest

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:fpm-alpine
