version: '3'
services:

  bind:
    image: cytopia/bind:alpine-0.35

  apache24:
    image: degobbis/apache24:latest

  php56:
    image: degobbis/php56:latest

  php73:
    image: degobbis/php73:latest

  php74:
    image: degobbis/php74:latest

  php80:
    image: degobbis/php80:latest

  php81:
    image: degobbis/php81:latest

  php82:
    image: degobbis/php82:latest

  php83:
    image: degobbis/php83:latest

  mariadb104:
    image: degobbis/mariadb104:latest

  mariadb105:
    image: degobbis/mariadb105:latest

  mariadb106:
    image: degobbis/mariadb106:latest

  mariadb1011:
    image: degobbis/mariadb1011:latest

  mysql57:
    image: degobbis/mysql57:latest

  mysql80:
    image: degobbis/mysql80:latest

  mysql83:
    image: degobbis/mysql83:latest

  mailcatcher:
    image: dockage/mailcatcher:latest

  phpmyadmin:
    image: phpmyadmin:fpm-alpine
