Listen 80
Listen 443

UseCanonicalName Off

<VirtualHost *:80>
    ServerAlias *
    ProxyPreserveHost On
    ProxyPass / http://localhost:${MAP_PORT_80}/
    ProxyPassReverse / http://localhost:${MAP_PORT_80}/
</VirtualHost>

<VirtualHost *:443>
    ServerAlias *
    SSLEngine On
    SSLProxyEngine On
    ProxyPreserveHost On
    ProxyPass / https://localhost:${MAP_PORT_443}/
    ProxyPassReverse / https://localhost:${MAP_PORT_443}/
</VirtualHost>

