  mysql57:
    image: degobbis/${MYSQL57_HOST_NAME}:latest
    container_name: ${COMPOSE_PROJECT_NAME}_${MYSQL57_HOST_NAME}
    restart: unless-stopped
    volumes:
      - ${MYSQL57_DATA_VOLUME}:/var/lib/mysql
      - ${APP_BASEDIR:-${DOCKER_LAMP_BASEDIR}/data}/${MYSQL57_DUMP_DIR}:/docker-entrypoint-initdb.d
    environment:
      TZ: ${MY_TZ:-UTC}
      LANG: ${MY_LOCALES:-en_GB.UTF-8}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD:-root}
      APP_USER_ID: ${APP_USER_ID:-1000}
      APP_GROUP_ID: ${APP_GROUP_ID:-1000}
      INIT_DB_BY_SCRIPT: 1
    ports:
      - "${MYSQL57_PORT:-3301}:3306"
    depends_on:
      - bind-internal
    networks:
      dlbridge:
        ipv4_address: ${DL_MYSQL57_IPv4}
        aliases: ${MYSQL57_ALIASES}
    dns:
      - ${DL_BIND_INTERNAL_IPv4:-}
